<?php
$lang = $this->model('lang');
?>
<h1 class="green-bar"><?php echo $lang['admin.category.header'] ?></h1>

<div class="cf">

	<div class="admin-box">
		<h3><?php echo $lang['admin.category.add'] ?></h3>

		<?php
		Ecl_Helper_Html::form('createcategoryform', $this->router()->makeAbsoluteUri('/admin/categories/create/') );
		?>
		<dl class="form">

			<dt><?php Ecl_Helper_Html::formLabel('name', $lang['admin.category.name']); ?></dt>
			<dd><?php Ecl_Helper_Html::formInput('name', 20, 250); ?></dd>

		</dl>

		<?php Ecl_Helper_Html::formSubmit('submitadd', $lang['admin.category.next'].' &gt;'); ?>

		<?php Ecl_Helper_Html::formClose(); ?>
	</div>



	<div class="admin-box">
		<h3><?php echo $lang['admin.category.rebuildh'] ?></h3>
		<p><?php echo $lang['admin.category.note'] ?></p>
			<?php
				Ecl_Helper_Html::form('rebuildcountsform', $this->router()->makeAbsoluteUri('/admin/categories/rebuildcounts/') );
				Ecl_Helper_Html::formSubmit('submitrebuild', $lang['admin.category.rebuildsubmit']);
				Ecl_Helper_Html::formClose();
				?>
	</div>



	<div class="admin-box">
		<h3><?php echo $lang['admin.category.cpvh'] ?></h3>
		<p><?php echo $lang['admin.category.cpvnote'] ?></p>
			<?php
			Ecl_Helper_Html::form('rebuildcountsform', $this->router()->makeAbsoluteUri('/admin/categories/cpvcodes') );
			Ecl_Helper_Html::formSubmit('submitcpvcodes', $lang['admin.category.cpvcfg']);
			Ecl_Helper_Html::formClose();
			?>
	</div>

	<p><?php echo $lang['admin.category.note'] ?></p>
	<p><?php echo $lang['admin.category.note2'] ?></p>

	<?php
	if ($this->categories->count()==0) {
		?>
		<p class="warning"><?php echo $lang['admin.category.warning'] ?></p>
		<?php
	} else {
		?>
		<ul>
			<?php
			$url = $this->router()->makeAbsoluteUri('/admin/categories/edit/?id=');
			foreach($this->categories as $i => $category) {
				?>
				<li><a href="<?php $this->out($url . $category->id); ?>"><?php $this->out($category->name); ?> <span class="count">(<?php $this->out($category->getItemCount()); ?>)</span></a></li>
				<?php
			}
			?>
		</ul>
		<?php
	}
	?>

</div>


