<?php 

$lang = $this->model('lang');

?>

<h1> <?php echo $lang['error.404.header'] ?> </h1>

<p> <?php echo $lang['error.404.note'] ?> </p>

<h2> <?php echo $lang['error.404.next'] ?> </h2>
<ul>
	<li> <?php echo $lang['error.404.listone'] ?> </li>
	<li> <?php echo $lang['error.404.listtwo'] ?> </li>
	<li> <?php echo $lang['error.404.listthree'] ?> </li>
	<li> <?php echo $lang['error.404.listfour'] ?> <a href="<?php echo($this->router()->makeAbsoluteUri()); ?>"> <?php echo $lang['error.404.homepagelink'] ?> </a></li>
</ul>
