<?php
$lang = $this->model('lang');
?>

<h1><?php echo $lang['admin.access.header'] ?></h1>


<div class="cf">

	<div class="admin-box">
		<h3><?php echo $lang['admin.access.add'] ?></h3>
		<?php
		Ecl_Helper_Html::form('accesslevelform', $this->router()->makeAbsoluteUri('/admin/accesslevels/create/'));
		Ecl_Helper_Html::formHidden('session_key', $this->model('user')->getSessionKey());
		?>
		<dl>
			<dt><?php Ecl_Helper_Html::formLabel('name', $lang['admin.access.name_label']); ?></dt>
			<dd><?php Ecl_Helper_Html::formInput('name', 20, 250); ?></dd>
		</dl>

		<div>
			<?php
			Ecl_Helper_Html::formSubmit('submitadd', $lang['admin.access.submit_label']);
			?>
		</div>
	</div>

	<p><?php echo $lang['admin.access.note'] ?></p>

	<?php
	if ($this->accesslevels->count()==0) {
		?>
		<p class="warning"><?php echo $lang['admin.access.warning'] ?></p>
		<?php
	} else {
		?>
		<ul>
			<?php
			foreach($this->accesslevels as $i => $accesslevel) {
				$edit_url = $this->router()->makeAbsoluteUri("/admin/accesslevels/edit/{$accesslevel->id}");
				printf('<li><a href="%2$s">%1$s%3$s</a></li>', Ecl_Helper_Html::escape($accesslevel->name), $edit_url, ( !empty($accesslevel->code) ? " &nbsp;({$accesslevel->code})" : '' ) );
			}
			?>
		</ul>
		<?php
	}
	?>


</div>
