<?php

$user = $this->model('user');
$lang = $this->model('lang');

?>

<h1><?php $this->out($lang['cat.label.plural']); ?></h1>

<?php
if ($this->categories->count()==0) {
	if ($this->model('user')->isAnonymous()) {
		?>
		<p class="note"><?php echo $lang['notes.category.private'] ?></p>
		<?php
	} else {
		?>
		<p class="note"> <?php echo $lang['notes.category.empty']  ?> </p>
		<?php
	}
}

if ($this->categories->count()>0) {

	if ($this->categories->count()>10) {
		$chunks = Ecl_Helper_Array::split($this->categories->toArray(), 2);
	} else {
		$chunks = array ( 0 => $this->categories );
	}
	?>
	<p class="note"><?php echo $lang['notes.category.list']?></p>

	<div id="categories">
		<table class="layout" style="width: 900px; margin: 1em auto;">
		<tr>
		<?php
		foreach($chunks as $chunk) {
			if (!empty($chunk)) {
				?>
				<td>
					<ul>
						<?php
						foreach($chunk as $i => $category) {
							if (false) {
								?>
								<li><a href="<?php echo $this->router()->makeAbsoluteUri("/{$lang['cat.route']}/{$category->slug}"); ?>"><?php $this->out($category->name); ?> <span class="count">(<?php $this->out($category->getItemCount($user->param('visibility'))); ?>)</span></a></li>
								<?php
							}
							?>
							<li><a href="<?php echo $this->router()->makeAbsoluteUri('/browse/'.strtolower($lang['cat.label'])."-{$category->id}-".$this->slugify($category->name)); ?>"><?php $this->out($category->name); ?> <span class="count">(<?php $this->out($category->getItemCount($user->param('visibility'))); ?>)</span></a></li>
							<?php
						}
						?>
					</ul>
				</td>
				<?php
			}
		}
		?>
		</tr>
		</table>
	</div>
	<?php
}?>
