<?php
$lang = $this->model('lang');
?>

<h1 class="green-bar"><?php echo $lang['admin.report.header'] ?></h1>
<p><?php echo $lang['admin.report.note'] ?></p>




<h3><?php echo $lang['admin.report.note'] ?></h3>
<ul>
	<li><a href="../inventory/"><?php echo $lang['admin.report.inv'] ?></a></li>
	<li><a href="../items/"><?php echo $lang['admin.report.itm'] ?></a></li>
	<li><a href="../staffcontacts/"><?php echo $lang['admin.report.stc'] ?></a></li>
	<li><a href="../manufacturers/"><?php echo $lang['admin.report.man'] ?></a></li>
</ul>


