<?php
$this->router()->layout()->addBreadcrumb('Custom Fields', $this->router()->makeAbsoluteUri('/admin/customfields/index/'));

$lang = $this->model('lang');
?>



<h1> <?php echo $lang['admin.cf.header'] ?>  </h1>
<p class="note"> <?php echo $lang['admin.cf.note']?> </p>
<p class="note"> <?php echo $lang['admin.cf.note2'] ?> </p>


<div class="cf">
	<div class="admin-box">
		<h3> <?php echo $lang['admin.cf.add_new'] ?> </h3>
		<?php
		Ecl_Helper_Html::form('customisationform', $this->router()->makeAbsoluteUri('/admin/customfields/create/'));
		Ecl_Helper_Html::formHidden('session_key', $this->model('user')->getSessionKey());
		?>
		<dl class="form">

			<dt><?php Ecl_Helper_Html::formLabel('name', $lang['admin.cf.fieldname']); ?></dt>
			<dd><?php Ecl_Helper_Html::formInput('name', 30, 250); ?></dd>

		</dl>

		<div>
			<?php Ecl_Helper_Html::formSubmit('submitadd', $lang['admin.cf.add']); ?>
		</div>

		<?php
		Ecl_Helper_Html::formClose();
		?>
	</div>



<?php
if (empty($this->custom_fields)) {
	?>
	<div class="warning"> <?php echo $lang['admin.cf.warning'] ?> </div>
	<?php
} else {
	?>
	<br />
	<p> <?php echo $lang['admin.cf.list'] ?> </p>
	<ul>
		<?php
		$edit_stub = $this->router()->makeAbsoluteUri('/admin/customfields/edit/');
		foreach($this->custom_fields as $field) {
			$edit_url = $edit_stub . urlencode($field->id);
			printf('<li><a href="%2$s">%1$s</a></li>', Ecl_Helper_Html::escape($field->name), $edit_url );
		}
		?>
	</ul>
	<?php
}
?>



</div>
