<?php 
$lang = $this->model('lang');
?>

<h1><?php echo $lang['admin.sites.header'] ?></h1>

<div class="cf">


	<div class="admin-box">
		<h3><?php echo $lang['admin.sites.add'] ?></h3>
		<?php
		Ecl_Helper_Html::form('siteform', $this->router()->makeAbsoluteUri('/admin/sites/create/'));
		Ecl_Helper_Html::formHidden('session_key', $this->model('user')->getSessionKey());
		?>
		<dl class="form">
			<dt><?php Ecl_Helper_Html::formLabel('name', $lang['admin.sites.label'] ); ?></dt>
			<dd><?php Ecl_Helper_Html::formInput('name', 20, 250); ?></dd>
		</dl>

		<?php Ecl_Helper_Html::formSubmit('submitadd', $lang['admin.sites.submit']); ?>

	</div>


	<p><?php echo $lang['admin.sites.note'] ?></p>

	<?php
	if ($this->sites->count()==0) {
		?>
		<p class="warning"><?php echo $lang['admin.sites.warning'] ?></p>
		<?php
	} else {
		?>
		<ul>
			<?php
			foreach($this->sites as $i => $site) {
				$edit_url = $this->router()->makeAbsoluteUri("/admin/sites/edit/{$site->id}");
				printf('<li><a href="%2$s">%1$s%3$s</a></li>', Ecl_Helper_Html::escape($site->name), $edit_url, ( !empty($site->code) ? " &nbsp;({$site->code})" : '' ) );
			}
			?>
		</ul>
		<?php
	}
	?>


</div>


