<?php 
$lang = $this->model('lang');
?>

<h1> <?php echo $lang['admin.hp.header'] ?> </h1>
<p> <?php echo $lang['admin.hp.explanation'] ?> </p>

<div class="cf">
	<div class="admin-box">
		<p> <?php echo $lang['admin.hp.boxtext'] ?> </p>
		<?php
		Ecl_Helper_Html::form('blockform', $this->router()->makeAbsoluteUri('/admin/homepageblocks/create/'));
		Ecl_Helper_Html::formHidden('session_key', $this->model('user')->getSessionKey());
		?>

		<dl class="form">

			<dt><?php Ecl_Helper_Html::formLabel('new_block', $lang['admin.hp.blockname']); ?></dt>
			<dd><?php Ecl_Helper_Html::formInput('new_block', 30, 250); ?></dd>

		</dl>

		<?php Ecl_Helper_Html::formSubmit('submitadd', $lang['admin.hp.blockadd']); ?>

		<?php Ecl_Helper_Html::formClose(); ?>

	</div>

	<?php
	if ($this->blocks->count()==0) {
		?>
		<p> <?php echo $lang['admin.hp.count0'] ?> </p>
		<p></p>
		<?php
	} else {
		?>
		<p> <?php echo $lang['admin.hp.list'] ?> </p>
		<ul>
			<?php
			foreach($this->blocks as $i => $block) {
				$edit_url = $this->router()->makeAbsoluteUri("/admin/homepageblocks/edit/{$block->block_id}");
				printf('<li><a href="%2$s">%1$s</a></li>', Ecl_Helper_Html::escape($block->block_name), $edit_url);
			}
			?>
		</ul>
		<?php
	}
	?>

</div>


