<?php
?>

<h1>Customise Item Fields</h1>
<p class="note"> <?php echo $lang['admin.cf.note'] ?> </p>
<p class="note"> <?php echo $lang['admin.cf.note2'] ?>

<br />
<?php
if (empty($this->custom_fields)) {
	?>
	<div class="warning"> <?php echo $lang['admin.cf.warning'] ?> </div>
	<?php
} else {
	?>
	<h4> <?php echo $lang['admin.cf.existing'] ?> </h4>
	<ul>
	<?php
	foreach($this->custom_fields as $field) {
		echo('<li>'. Ecl_Helper_Html::escape($field->name) .'</li>');
	}
	?>
	</ul>
	<?php
}
?>

<br />
<h4> <?php echo $lang['admin.cf.add_new'] ?> </h4>
<?php
Ecl_Helper_Html::form('customisationform', $this->router()->makeAbsoluteUri('/admin/items/customise/'));
Ecl_Helper_Html::formHidden('session_key', $this->model('user')->getSessionKey());
Ecl_Helper_Html::formInput('name', 30, 100);
Ecl_Helper_Html::formSubmit('submitadd', 'Add Field');
Ecl_Helper_Html::formClose();
?>

