<?php
$lang = $this->model('lang');
$user = $this->model('user');

$item = $this->item;
$new_item = empty($item->id);


$this->layout()->addGlobalJavascript();

$this->layout()->appendSection('layout.head', <<<EndJS
<script type="text/javascript">

	var link_element_count = 1;
	var file_element_count = 1;

	$(document).ready( function() {

		var del_button = $('<input type="submit" name="submitdelete" value="Delete Item" />');
		del_button.click(function () {
			var msg = 'Please confirm that this item and its associated files will be deleted.\\n\\nThis operation cannot be undone.';
			return confirm(msg);
		});
		$('#delete_button_container').append(del_button);


		var addlinkmore_button = $('<input type="button" name="addlinkmore" value="More Links.." />');
		addlinkmore_button.click(function() {
			link_element_count++;
			var id_prefix = 'link_'+ link_element_count +'_';
			var el_prefix = 'newlink['+ link_element_count +']';
			new_link_block = $('<dt><label>Link '+ link_element_count +'</label></dt><dd><label for="'+ id_prefix +'name" >Title</label><br /><input type="text" name="'+ el_prefix +'[name]" id="'+ id_prefix +'name" size="40" maxlength="250" value="" /><br /><label for="'+ id_prefix +'url" >URL</label><br /><input type="text" name="'+ el_prefix +'[url]" id="'+ id_prefix +'url" size="65" maxlength="250" value="" /></dd>');
			$('#addlink_list').append(new_link_block);
		});
		$('#addlinksmore_button_container').append(addlinkmore_button);


		var uploadmore_button = $('<input type="button" name="uploadmore" value="More Files.." />');
		uploadmore_button.click(function() {
			file_element_count++;
			new_upload_block = $('<dt><label for="file_'+ file_element_count +'">File '+ file_element_count +'</label></dt><dd><input type="file" name="file_'+ file_element_count +'" id="file_'+ file_element_count +'" /></dd>');
			$("#upload dl").append(new_upload_block);
		});
		$('#uploadmore_button_container').append(uploadmore_button);


		var usemyemail1_button = $('<input type="button" name="usemyemail" value="Use my email" />');
		usemyemail1_button.click(function() {
			$("input#new_contact_1_email").val("{$user->email}");
		});
		$("#td_contact1email").append(usemyemail1_button);


		var usemyemail2_button = $('<input type="button" name="usemyemail" value="Use my email" />');
		usemyemail2_button.click(function() {
			$("input#new_contact_2_email").val("{$user->email}");
		});
		$("#td_contact2email").append(usemyemail2_button);


	});

</script>
EndJS
);
?>



<?php
Ecl_Helper_Html::form('itemform', $this->request()->uri(), 'post', 'UTF-8', 'enctype="multipart/form-data"');
Ecl_Helper_Html::formHidden('item_id', $item->id);
?>


<?php Ecl_Helper_Html::formSubmitUnique('submitsave', 'Save Changes', 'style="position: absolute; left: -100%;"'); ?>


<div id="delete_button_container"></div>


<h1><?php echo $lang['admin.edititem.header_edit']; $this->out( ($new_item) ? $lang['admin.edititem.new_item'] : $item->name ); ?></h1>
<div style="margin-bottom: 1em;"><a href="<?php echo $this->backlink; ?>">&laquo; <?php echo $lang['admin.edititem.back']?></a></div>


<p class="note"><?php echo $lang['admin.edititem.required'] ?></p>

<fieldset>
	<legend><?php $this->out($lang['item.formsection.main']); ?></legend>

	<?php
	if (!empty($item->date_updated)) {
		?>
		<div class="itemedit_sidestatus">
			<p><?php echo $lang['admin.edititem.last_updated'];
				
				if (!empty($item->last_updated_by)) {
					?>
					<br /><?php $this->out($item->last_updated_by); ?>
					<?php
				}
				?>
				<br /><?php echo date($this->model('layout.date_format'), $item->date_updated); ?>.
		</div>
		<?php
	}

	if ($item->visibility == KC__VISIBILITY_PUBLIC) {
		?>
		<div class="itemedit_sidestatus" style="background-color: #fdd;">
			<p><?php echo $lang['admin.edititem.visible_public'] ?></p>
		</div>
		<?php
	}
	?>

	<dl class="form">
		<dt><?php Ecl_Helper_Html::formLabel('title', $lang['item.form.title'].' *'); ?></dt>
		<dd>
			<p class="note"><?php echo $lang['admin.edititem.name_note'] ?></p>
			<?php Ecl_Helper_Html::formInput('title', 70, 250, $item->title); ?>
		</dd>

		<dt><?php Ecl_Helper_Html::formLabel('manufacturer', $lang['item.form.manufacturer'].' *'); ?></dt>
		<dd>
			<p class="note"><?php echo $lang['admin.edititem.manufacturer_note'] ?></p>
			<?php Ecl_Helper_Html::formInput('manufacturer', 40, 100, $item->manufacturer); ?>
		</dd>

		<dt><?php Ecl_Helper_Html::formLabel('model', $lang['item.form.model']); ?></dt>
		<dd><?php Ecl_Helper_Html::formInput('model', 40, 100, $item->model); ?></dd>

		<dt><?php Ecl_Helper_Html::formLabel('ou', $lang['ou.label'].' *'); ?></dt>
		<dd>
			<p class="note"><?php echo $lang['admin.edititem.ou_note'] ?></p>
			<?php
			if (!$this->layout()->renderOUSelect('ou', $item->ou)) {
				$ou_name = $this->model('organisationalunitstore')->lookupName($item->ou);
				?>
				<strong><?php $this->out($ou_name); ?></strong>
				<br /><span class="note"><?php echo $lang['admin.edititem.ou_help'] ?></span>
				<?php
			}
			?>
		</dd>

		<dt id="changevis"><?php Ecl_Helper_Html::formLabel('visibility', $lang['item.form.visibility'].' *'); ?></dt>
		<dd>
			<p class="note"><?php echo $lang['admin.edititem.visibility'] ?></p>
			<?php
			$options = array(
				//KC__VISIBILITY_DRAFT  => 'Draft' ,
				KC__VISIBILITY_INTERNAL  => $lang['admin.edititem.internal_only'] ,
				KC__VISIBILITY_PUBLIC    => $lang['admin.edititem.public'] ,
			);

			Ecl_Helper_Html::formSelect('visibility', $options, $item->visibility);
			?>
		</dd>

	</dl>
</fieldset>


<div style="text-align: center;">
	<?php Ecl_Helper_Html::formSubmitUnique('submitsave', $lang['admin.edititem.save_changes']); ?>
</div>


<fieldset>
	<legend><?php $this->out($lang['item.formsection.contact']); ?></legend>

	<dl class="form">
		<dt><?php $this->out($lang['item.form.contact_1']); ?> *</dt>
		<dd>
			<p class="note"><?php echo $lang['admin.edititem.custodian'] ?></p>
			<dl class="form">

				<dt><?php Ecl_Helper_Html::formLabel('contact_1_name', $lang['admin.edititem.name_label']); ?></dt>
				<dd><?php Ecl_Helper_Html::formInput('contact_1_name', 40, 250, $item->contact_1_name); ?></dd>

				<dt><?php echo $lang['admin.edititem.mail_label'] ?> *</dt>
				<dd>
					<table class="layout">
					<tr>
						<td>
							<label style="display: block;" for="contact_1_email"><?php echo $lang['admin.edititem.select_mail'] ?></label>
							<select name="contact_1_email" id="contact_1_email">
								<?php
								$options = $this->model('itemstore')->findAllContacts(KC__VISIBILITY_INTERNAL);

								array_walk($options, function(&$v, $k) {
									$v = strtolower($v);
								});

								$options = Ecl_Helper_Array::duplicateValueAsKey($options);
								$options = array('' => '') + $options;

								Ecl_Helper_Html::formOptions($options, strtolower($item->contact_1_email));
								?>
							</select>
						</td>
						<td id="td_contact1email" style="padding-left: 2em;">
							<label style="display: block;" for="new_contact_1_email">&hellip;<?php echo $lang['admin.edititem.existing_mail'] ?></label>
							<?php
							Ecl_Helper_Html::formInput('new_contact_1_email', 40, 250, $this->request()->post('new_contact_1_email'));
							?>
						</td>
					</tr>
					</table>
				</dd>

			</dl>
		</dd>

	</dl>

	<hr />

	<dl class="form">

		<dt><?php $this->out($lang['item.form.contact_2']); ?></dt>
		<dd>
			<p class="note"><?php echo $lang['admin.edititem.secondary_staff'] ?></p>
			<dl class="form">

				<dt><?php Ecl_Helper_Html::formLabel('contact_2_name', $lang['admin.edititem.name_label']); ?></dt>
				<dd><?php Ecl_Helper_Html::formInput('contact_2_name', 40, 250, $item->contact_2_name); ?></dd>

				<dt><?php echo $lang['admin.edititem.mail_label'] ?></dt>
				<dd>
					<table class="layout">
					<tr>
						<td>
							<label style="display: block;" for="contact_2_email"><?php echo $lang['admin.edititem.select_mail'] ?></label>
							<select name="contact_2_email" id="contact_2_email">
								<?php
								$options = $this->model('itemstore')->findAllContacts(KC__VISIBILITY_INTERNAL);

								array_walk($options, function(&$v, $k) {
									$v = strtolower($v);
								});

								$options = Ecl_Helper_Array::duplicateValueAsKey($options);
								$options = array('' => '') + $options;

								Ecl_Helper_Html::formOptions($options, strtolower($item->contact_2_email));
								$options = null;
								?>
							</select>
						</td>
						<td id="td_contact2email" style="padding-left: 2em;">
							<label style="display: block;" for="new_contact_2_email">&hellip;<?php echo $lang['admin.edititem.existing_mail'] ?></label>
							<?php
							Ecl_Helper_Html::formInput('new_contact_2_email', 40, 250, $this->request()->post('new_contact_2_email'));
							?>
						</td>
					</tr>
					</table>
				</dd>

			</dl>
		</dd>

	</dl>

</fieldset>


<div style="text-align: center;">
	<?php Ecl_Helper_Html::formSubmitUnique('submitsave', $lang['admin.edititem.save_changes']); ?>
</div>



<?php
if ($this->model('admin.item.editors.enabled')) {
	?>

	<fieldset>
		<legend><?php $this->out($lang['item.formsection.editors']); ?></legend>

		<p class="note"><?php echo $lang['admin.edititem.editor_note']?></p>

		<dl class="form">

			<?php
			if ($this->model('security')->checkItemPermission($item, 'item.editors.edit')) {
				?>

			<dt><?php echo $lang['admin.edititem.add_editor'] ?></dt>
			<dd>
				<p class="note"><?php echo $lang['admin.edititem.enter_editornames'] ?></p>
				<?php
				Ecl_Helper_Html::formTextarea('new_editors', 20, 3, '');
				?>
			</dd>

				<?php
			}
			?>

			<dt><?php echo $lang['admin.edititem.current_editors'] ?></dt>
			<?php
			$editors = $this->model('itemeditorstore')->findForItem($item->id);
			if (0 == $editors->count()) {
				?>
				<dd><?php echo $lang['admin.edititem.none'] ?></dd>
				<?php
			} else {
				?>
				<dd>
					<?php
					if ($this->model('security')->checkItemPermission($item, 'item.editors.edit')) {
						?>
						<p class="note"><?php echo $lang['admin.edititem.to_remove_tick'] ?></p>
						<table class="grid">
						<tr>
							<th style="text-align: center;"><?php echo $lang['admin.edititem.username'] ?></th>
							<th style="text-align: center;"><?php echo $lang['admin.edititem.remove'] ?></th>
						</tr>
						<?php
						$i = 0;
						foreach($editors as $editor) {
							$i++;
							printf('<tr><td class="name"><label for="remove_editors_%1$s">%2$s</label></td><td class="checkbox"><input type="checkbox" name="remove_editors[]" id="remove_editors_%3$s" value="%1$s" /></td></tr>', $this->escape($editor->id), $this->escape($editor->username), $i);
						}
						?>
						</table>
						<?php
					} else {
						?>
						<table class="grid">
						<tr>
							<th style="text-align: center;"><?php echo $lang['admin.edititem.username'] ?></th>
						</tr>
						<?php
						foreach($editors as $editor) {
							printf('<tr><td class="name">%1$s</td></tr>', $this->escape($editor->username));
						}
						?>
						</table>
						<?php
					}
					?>
				</dd>
				<?php
			}
			?>

		</dl>
	</fieldset>

	<div style="text-align: center;">
		<?php Ecl_Helper_Html::formSubmitUnique('submitsave', $lang['admin.edititem.save_changes']); ?>
	</div>
	<?php
}
?>


<fieldset>
	<legend><?php $this->out($lang['item.formsection.description']); ?></legend>

	<dl class="form">

		<dt><?php Ecl_Helper_Html::formLabel('short_description', $lang['item.form.short_description']); ?></dt>
		<dd>
			<p class="note"><?php echo $lang['admin.edititem.short_desc_note'] ?></p>
			<?php Ecl_Helper_Html::formTextarea('short_description', 80, 2, $item->short_description); ?>
		</dd>

		<dt><?php Ecl_Helper_Html::formLabel('full_description', $lang['item.form.full_description']); ?></dt>
		<dd>
			<p class="note"> <?php echo $lang['admin.edititem.full_desc_note'] ?> </p>
			<?php Ecl_Helper_Html::formTextarea('full_description', 80, 7, $item->full_description); ?>
			<p class="note" style="text-align: center;"> <?php echo $lang['admin.edititem.wikitext'] ?> </p>
		</dd>

		<dt><?php Ecl_Helper_Html::formLabel('specification', $lang['item.form.specification']); ?></dt>
		<dd>
			<p class="note"> <?php echo $lang['admin.edititem.technical_desc'] ?> </p>
			<?php Ecl_Helper_Html::formTextarea('specification', 80, 3, $item->specification); ?>
			<p class="note" style="text-align: center;"> <?php echo $lang['admin.edititem.wikitext'] ?> </p>
		</dd>

		<dt><?php Ecl_Helper_Html::formLabel('upgrades', $lang['item.form.upgrades']); ?></dt>
		<dd>
			<p class="note"> <?php echo $lang['admin.edititem.upgrades_note'] ?> </p>
			<?php Ecl_Helper_Html::formTextarea('upgrades', 80, 2, $item->upgrades); ?>
		</dd>

		<dt><?php Ecl_Helper_Html::formLabel('future_upgrades', $lang['item.form.future_upgrades']); ?></dt>
		<dd>
			<p class="note"> <?php echo $lang['admin.edititem.future_upgrades_note'] ?> </p>
			<?php Ecl_Helper_Html::formTextarea('future_upgrades', 80, 2, $item->future_upgrades); ?>
		</dd>

		<dt><?php Ecl_Helper_Html::formLabel('manufacturer_website', $lang['item.form.manufacturer_website']); ?></dt>
		<dd>
			<p class="note"> <?php echo $lang['admin.edititem.manufacturer_website_note'] ?> </p>
			<?php Ecl_Helper_Html::formInput('manufacturer_website', 80, 250, $item->manufacturer_website); ?>
		</dd>

		<dt><?php Ecl_Helper_Html::formLabel('technique', $lang['item.form.technique']); ?></dt>
		<dd>
			<p class="note"> <?php echo $lang['admin.edititem.technique_note'] ?> </p>
			<?php Ecl_Helper_Html::formInput('technique', 30, 100, $item->technique); ?>
		</dd>

		<dt><?php Ecl_Helper_Html::formLabel('acronym', $lang['item.form.acronym']); ?></dt>
		<dd>
			<p class="note"> <?php echo $lang['admin.edititem.acronym'] ?> </p>
			<?php Ecl_Helper_Html::formInput('acronym', 10, 15, $item->acronym); ?>
		</dd>

		<dt><?php Ecl_Helper_Html::formLabel('keywords', $lang['item.form.keywords']); ?></dt>
		<dd>
			<p class="note"> <?php echo $lang['admin.edititem.keywords_1'] ?> </p>
			<p class="note"> <?php echo $lang['admin.edititem.keywords_2'] ?> </p>
			<?php Ecl_Helper_Html::formInput('keywords', 80, 250, $item->keywords); ?>
		</dd>

		<dt><?php Ecl_Helper_Html::formLabel('tags', $lang['tag.label.plural']); ?></dt>
		<dd>
			<p class="note"> <?php echo $lang['admin.edititem.tags_1'] ?> </p>
			<p class="note"> <?php echo $lang['admin.edititem.tags_2'] ?> </p>
			<p class="note"> <?php echo $lang['admin.edititem.tags_3'] ?> </p>
			<?php
			if ($item->id || $this->saved_ok) {
				$tags = $this->model('itemstore')->getItemTags($item->id);

				// Remove any preceding '#' symbols
				array_walk($tags, function (&$v) {
					if ( (strlen($v)>1) && ('#' == $v[0]) )  {
						$v = substr($v, 1);
					}
				});

				$tags = implode(', ', $tags);
			} else {
				$tags = $this->request()->post('tags');
			}
			Ecl_Helper_Html::formInput('tags', 80, 2048, $tags);
			?>
		</dd>

	</dl>
</fieldset>


<div style="text-align: center;">
	<?php Ecl_Helper_Html::formSubmitUnique('submitsave', $lang['admin.edititem.save_changes']); ?>
</div>


<fieldset>
	<legend><?php $this->out($lang['item.formsection.parent']); ?></legend>

	<dl class="form">

		<dt><?php $this->out($lang['item.form.is_parent']); ?></dt>
		<dd>
			<?php
			$options = array(
				'1' => $lang['admin.edititem.parent_1'] ,
				'0' => $lang['admin.edititem.parent_2'] ,
			);
			$selected = (int) $item->is_parent;

			Ecl_Helper_Html::formRadioGrid('is_parent', $options, 1, $selected);
			?>
		</dd>

		<?php
		if ($item->is_parent) {
			$temp_children = $this->model('itemstore')->findChildren($item->id);
			$options = array();
			$selected = array();
			foreach($temp_children as $child) {
				$options[$child->id] = $child->name;
				$selected[] = $child->id;
			}
			$temp_children = null;
			?>
			<dt><?php $this->out($lang['item.form.showchildren']); ?></dt>
			<dd>
				<?php
				if (empty($options)) {
					echo('<p>'.$lang['admin.edititem.nochild'].'</p>');
				} else {
					echo('<p class="note">'.$lang['admin.edititem.nochild'].'</p>');
					if (10 > count($options)) {
						Ecl_Helper_Html::formCheckboxGrid('children', $options, 2, $selected);
					} else {
						echo '<div class="scrollable">';
						Ecl_Helper_Html::formCheckboxGrid('children', $options, 2, $selected);
						echo '</div>';
					}
				}
				?>
				<br />
				<p class="note"><?php echo $lang['admin.edititem.addchild'] ?></p>
			</dd>
			<?php
		}
		?>

	</dl>

	<hr />

	<dl class="form">

		<?php
		$temp_facilities = $this->model('itemstore')->findAllParents($item->id);
		if (!empty($temp_facilities)) {
			$options = array();
			foreach($temp_facilities as $facility) {
				$options[$facility->id] = $facility->name;
			}
			$temp_facilities = null;

			$selected = $this->model('itemstore')->findParents($item->id)->toColumn('id');
			?>
			<dt><?php $this->out($lang['item.form.selectparent']); ?></dt>
			<dd>
				<?php
				if (empty($options)) {
					echo('<p>'.$lang['admin.edititem.noparents'].'</p>');
				} else {
					echo('<p class="note">'.$lang['admin.edititem.removefacility'].'</p>');
					if (10 > count($options)) {
						Ecl_Helper_Html::formCheckboxGrid('parents', $options, 2, $selected);
					} else {
						echo '<div class="scrollable">';
						Ecl_Helper_Html::formCheckboxGrid('parents', $options, 2, $selected);
						echo '</div>';
					}
				}
				?>
			</dd>
			<?php
		}
		?>

	</dl>

</fieldset>


<div style="text-align: center;">
	<?php Ecl_Helper_Html::formSubmitUnique('submitsave', $lang['admin.edititem.save_changes']); ?>
</div>


<fieldset>
	<legend><?php $this->out($lang['item.formsection.categorisation']); ?></legend>

	<dl class="form">

		<dt><?php echo $lang['admin.edititem.associated'] ?></dt>
		<dd>
			<?php
			if ($new_item) {
				$selected = $this->request()->post('category');
			} else {
				$selected = $this->model('categorystore')->findForItem($item->id)->toColumn('id');
			}
			Ecl_Helper_Html::formCheckboxGrid('category', $this->model('categorystore')->findAll()->toAssoc('id', 'name'), 3, $selected);
			?>
			&nbsp; &nbsp;
			<label style="display: block;" for="other_category">&hellip;<?php echo $lang['admin.edititem.use_new'] ?></label>
			<?php
			Ecl_Helper_Html::formInput('other_category', 40, 250, $this->request()->post('other_category'));
			?>
		</dd>

	</dl>
</fieldset>


<div style="text-align: center;">
	<?php Ecl_Helper_Html::formSubmitUnique('submitsave', $lang['admin.edititem.save_changes']); ?>
</div>


<fieldset>
	<legend><?php $this->out($lang['item.formsection.access']); ?></legend>

	<dl class="form">

		<dt><?php Ecl_Helper_Html::formLabel('access', $lang['access.label']); ?></dt>
		<dd>
			<p class="note"><?php echo $lang['admin.edititem.access_note'] ?></p>
			<?php
			$options = (array) $this->model('accesslevelstore')->findAll()->toAssoc('id', 'name');
			$options = array('0' => '') + $options;

			Ecl_Helper_Html::formSelect('access', $options, $item->access);
			?>
		</dd>

		<dt><?php Ecl_Helper_Html::formLabel('usergroup', $lang['item.form.usergroup']); ?></dt>
		<dd>
			<p class="note"><?php echo $lang['admin.edititem.usergroup_note'] ?></p>
			<?php Ecl_Helper_Html::formInput('usergroup', 30, 250, $item->usergroup); ?>
		</dd>

		<dt><?php Ecl_Helper_Html::formLabel('availability', $lang['item.form.availability']); ?></dt>
		<dd>
			<p class="note"><?php echo $lang['admin.edititem.available_note'] ?></p>
			<?php Ecl_Helper_Html::formInput('availability', 50, 250, $item->availability); ?>
		</dd>

		<dt><?php Ecl_Helper_Html::formLabel('restrictions', $lang['item.form.restrictions']); ?></dt>
		<dd>
			<p class="note"><?php echo $lang['admin.edititem.restriction_note'] ?></p>
			<?php Ecl_Helper_Html::formInput('restrictions', 50, 250, $item->restrictions); ?>
		</dd>

		<dt><?php Ecl_Helper_Html::formLabel('portability', $lang['item.form.portability']); ?></dt>
		<dd>
			<p class="note"><?php echo $lang['admin.edititem.portability_note'] ?></p>
			<?php Ecl_Helper_Html::formInput('portability', 30, 250, $item->portability); ?>
		</dd>

		<dt><?php Ecl_Helper_Html::formLabel('training_required', $lang['item.form.trainingrequired']); ?></dt>
		<dd>
			<p class="note"><?php echo $lang['admin.edititem.training_note'] ?></p>
			<?php
			$options = array (
				'1'   => $lang['admin.edititem.training_1'] ,
				'0'   => $lang['admin.edititem.training_2'] ,
				'n/s' => $lang['admin.edititem.training_3'] ,
				//'0'   => 'No training required.' ,
				//'n/s' => 'Not specified (not shown on site).' ,
			);


			if (is_null($item->training_required)) {
				$selected = 'n/s';
			} else {
				$selected = ($item->training_required) ? '1' : '0' ;
			}

			Ecl_Helper_Html::formRadioGrid('training_required', $options, 1, $selected);
			?>
		</dd>

		<dt><?php Ecl_Helper_Html::formLabel('training_provided', $lang['item.form.trainingprovided']); ?></dt>
		<dd>
			<p class="note"><?php echo $lang['admin.edititem.training_provided'] ?></p>
			<?php
			$options = array (
				'1' => $lang['admin.edititem.training_4'],
				'0' => $lang['admin.edititem.training_5'] ,
				'n/s' => $lang['admin.edititem.training_6'],
			);

			if (is_null($item->training_provided)) {
				$selected = 'n/s';
			} else {
				$selected = ($item->training_provided) ? '1' : '0' ;
			}

			Ecl_Helper_Html::formRadioGrid('training_provided', $options, 1, $selected);
			?>
		</dd>

		<dt><?php Ecl_Helper_Html::formLabel('calibrated', $lang['item.form.calibrated']); ?></dt>
		<dd>
			<p class="note"><?php echo $lang['admin.edititem.calibrated'] ?></p>
			<?php
			Ecl_Helper_Html::formRadio('calibrated', 'calibrated_yes', Item::CALIB_YES, (Item::CALIB_YES === $item->calibrated) );
			Ecl_Helper_Html::formLabel('calibrated_yes', $lang['admin.edititem.iscalibrated']);
			?>
			<table class="form" style="margin: 0 0 1em 4em;">
			<tr>
				<th><?php Ecl_Helper_Html::formLabel('last_calibration_date', $lang['item.form.last_calibration_date']); ?></th>
				<td><?php Ecl_Helper_Html::formSelectsDmyNullable('last_calibration_date', date('Y')-10, date('Y'), $item->last_calibration_date); ?></td>
			</tr>
			<tr>
				<th><?php Ecl_Helper_Html::formLabel('next_calibration_date', $lang['item.form.next_calibration_date']); ?></th>
				<td><?php Ecl_Helper_Html::formSelectsDmyNullable('next_calibration_date', date('Y')-10, date('Y')+10, $item->next_calibration_date); ?></td>
			</tr>
			</table>

			<?php
			Ecl_Helper_Html::formRadio('calibrated', 'calibrated_no', Item::CALIB_NO, (Item::CALIB_NO === $item->calibrated) );
			Ecl_Helper_Html::formLabel('calibrated_no', $lang['admin.edititem.calibrated_1'] );
			?>
			<br />
			<?php
			Ecl_Helper_Html::formRadio('calibrated', 'calibrated_auto', Item::CALIB_AUTO, (Item::CALIB_AUTO === $item->calibrated) );
			Ecl_Helper_Html::formLabel('calibrated_auto', $lang['admin.edititem.calibrated_2']);
			?>
			<br />
			<?php
			Ecl_Helper_Html::formRadio('calibrated', 'calibrated_notapp', Item::CALIB_NOTAPP, (Item::CALIB_NOTAPP === $item->calibrated) );
			Ecl_Helper_Html::formLabel('calibrated_notapp', $lang['admin.edititem.calibrated_3']);
			?>

		</dd>

		<dt><?php Ecl_Helper_Html::formLabel('quantity', $lang['item.form.quantity']); ?></dt>
		<dd><?php Ecl_Helper_Html::formInput('quantity', 5, 10, $item->quantity); ?></dd>

		<dt><?php Ecl_Helper_Html::formLabel('quantity_detail', $lang['item.form.quantity_detail']); ?></dt>
		<dd><p class="note"><?php echo $lang['admin.edititem.quantity_note'] ?></p>
			<?php Ecl_Helper_Html::formInput('quantity_detail', 50, 100, $item->quantity_detail); ?>
		</dd>

	</dl>
</fieldset>


<div style="text-align: center;">
	<?php Ecl_Helper_Html::formSubmitUnique('submitsave', $lang['admin.edititem.save_changes']); ?>
</div>


<fieldset>
	<legend><?php $this->out($lang['item.formsection.location']); ?></legend>

	<dl class="form">

		<dt><?php Ecl_Helper_Html::formLabel('site', $lang['site.label']); ?></dt>
		<dd>
			<?php
			$options = array('0' => '') + $this->model('sitestore')->findAll()->toAssoc('id', 'name');
			Ecl_Helper_Html::formSelect('site', $options, $item->site);
			?>
		</dd>

		<dt><?php Ecl_Helper_Html::formLabel('building', $lang['building.label']); ?></dt>
		<dd>
			<?php
			$options = array('0' => '') + $this->model('buildingstore')->findAll()->toAssoc('id', 'name');
			Ecl_Helper_Html::formSelect('building', $options, $item->building);
			?>
		</dd>

		<dt><?php Ecl_Helper_Html::formLabel('room', $lang['item.form.room']); ?></dt>
		<dd>
			<?php
			Ecl_Helper_Html::formInput('room', 15, 20, $item->room);
			?>
		</dd>

	</dl>

</fieldset>


<div style="text-align: center;">
	<?php Ecl_Helper_Html::formSubmitUnique('submitsave', $lang['admin.edititem.save_changes']); ?>
</div>


<fieldset><br>
	<legend><?php $this->out($lang['item.formsection.asset']); ?></legend>

	<dl class="form">

		<dt><?php Ecl_Helper_Html::formLabel('asset_no', $lang['item.form.asset_no']); ?></dt>
		<dd><?php Ecl_Helper_Html::formInput('asset_no', 15, 250, empty($item->asset_no) ? null : $item->asset_no ); ?></dd>

		<dt><?php Ecl_Helper_Html::formLabel('finance_id', $lang['item.form.finance_id']); ?></dt>
		<dd><?php Ecl_Helper_Html::formInput('finance_id', 15, 250, empty($item->finance_id) ? null : $item->finance_id ); ?></dd>

		<dt><?php Ecl_Helper_Html::formLabel('serial_no', $lang['item.form.serial_no']); ?></dt>
		<dd><?php Ecl_Helper_Html::formInput('serial_no', 15, 250, empty($item->serial_no) ? null : $item->serial_no ); ?></dd>

		<dt><?php Ecl_Helper_Html::formLabel('year_of_manufacture', $lang['item.form.year_of_manufacture']); ?></dt>
		<dd><?php Ecl_Helper_Html::formInput('year_of_manufacture', 10, 4, $item->year_of_manufacture); ?></dd>

		<dt><?php $this->out($lang['item.form.supplier']); ?></dt>
		<dd>
			<table class="layout">
			<tr>
				<?php
				$no_options = true;
				$options = $this->model('supplierstore')->findAll()->toAssoc('id', 'name');
				if (!empty($options)) {
					$no_options = false;
					?>
					<td style="padding-right: 2em;">
						<label style="display: block;" for="supplier">Select an existing <?php $this->out(strtolower($lang['item.form.supplier'])); ?></label>
						<?php
						$options = array ('' => '') + $options;
						Ecl_Helper_Html::formSelect('supplier', $options, $item->supplier);
						?>
					</td>
					<?php
				}
				?>
				<td>
					<?php
					if ($no_options) {
						?>
						<label style="display: block;" for="new_supplier"><?php echo $lang['admin.edititem.supplier'] ?></label>
						<?php
					} else {
						?>
						<label style="display: block;" for="new_supplier">&hellip;or provide a new <?php $this->out(strtolower($lang['item.form.supplier'])); ?></label>
						<?php
					}
					Ecl_Helper_Html::formInput('new_supplier', 30, 250, $this->request()->post('new_supplier'));
					?>
				</td>
			</tr>
			</table>

		</dd>

		<dt><?php Ecl_Helper_Html::formLabel('PAT', $lang['item.form.PAT']); ?></dt>
		<dd><?php Ecl_Helper_Html::formSelectsDmyNullable('PAT', date('Y'), date('Y')+10, empty($item->PAT) ? null : $item->PAT ); ?></dd>

		<dt><?php Ecl_Helper_Html::formLabel('cost', $lang['item.form.cost']); ?></dt>
		<dd><?php Ecl_Helper_Html::formInput('cost', 30, 100, $item->cost); ?></dd>

		<dt><?php Ecl_Helper_Html::formLabel('date_of_purchase', $lang['item.form.date_of_purchase']); ?></dt>
		<dd><?php Ecl_Helper_Html::formSelectsDmyNullable('date_of_purchase', date('Y')-20, date('Y'), empty($item->date_of_purchase) ? null : $item->date_of_purchase); ?></dd>

		<dt><?php Ecl_Helper_Html::formLabel('replacement_cost', $lang['item.form.replacement_cost']); ?></dt>
		<dd><?php Ecl_Helper_Html::formInput('replacement_cost', 30, 100, $item->replacement_cost); ?></dd>

		<dt><?php Ecl_Helper_Html::formLabel('end_of_life', $lang['item.form.end_of_life']); ?></dt>
		<dd><?php Ecl_Helper_Html::formSelectsDmyNullable('end_of_life', date('Y')-5, date('Y')+10, empty($item->end_of_life) ? null : $item->end_of_life); ?></dd>

		<dt><?php Ecl_Helper_Html::formLabel('maintenance', $lang['item.form.maintenance']); ?></dt>
		<dd>
			<p class="note"><?php echo $lang['admin.edititem.maintenance'] ?></p>
			<?php Ecl_Helper_Html::formInput('maintenance', 100, 250, $item->maintenance); ?>
		</dd>

		<dt><?php Ecl_Helper_Html::formLabel('is_disposed_of', $lang['item.form.is_disposed_of']); ?></dt>
		<dd>
			<p class="note"><?php echo $lang['admin.edititem.disposed'] ?></p>
			<!-- Such items will remain on the catalogue until archived (see below) -->
			<?php
			$options = array(
				Item::DISPOSED_NO    => $lang['admin.edititem.disposed_1'] ,
				Item::DISPOSED_SOLD  => $lang['admin.edititem.disposed_2'] ,
				Item::DISPOSED_SCRAP => $lang['admin.edititem.disposed_3'] ,
			);
			Ecl_Helper_Html::formSelect('is_disposed_of', $options, $item->is_disposed_of);
			?>
		</dd>

		<dt><?php Ecl_Helper_Html::formLabel('date_disposed_of', $lang['item.form.date_disposed_of']); ?></dt>
		<dd><?php Ecl_Helper_Html::formSelectsDmyNullable('date_disposed_of', date('Y')-5, date('Y'), empty($item->date_disposed_of) ? null : $item->date_disposed_of); ?></dd>

<?php
// @todo : Enable archive-status items
if (false) {
	?>
		<dt><?php Ecl_Helper_Html::formLabel('archived', $lang['item.form.archived']); ?></dt>
		<dd>
			<p class="note"><?php echo $lang['admin.edititem.archive_note1'] ?></p>
			<p class="note"><?php echo $lang['admin.edititem.archive_note2'] ?></p>
			<?php
			$options = array(
				'0' => $lang['admin.edititem.archive.active'] ,
				'1' => $lang['admin.edititem.archive_inactive'] ,
			);
			Ecl_Helper_Html::formSelect('disposed_of', $options, $item->disposed_of);
			?>
		</dd>
	<?php
}
?>

		<dt><?php Ecl_Helper_Html::formLabel('comments', $lang['item.form.comments']); ?></dt>
		<dd>
			<p class="note"><?php echo $lang['admin.edititem.comment_note'] ?></p>
			<?php Ecl_Helper_Html::formTextarea('comments', 80, 4, $item->comments); ?>
		</dd>

	</dl>

</fieldset>


<?php
$fields = $this->model('customfieldstore')->findAll();
if (!empty($fields)) {
	$item_custom = $this->model('itemstore')->getItemCustomFields($item->id);
	?>
	<fieldset>
		<legend><?php $this->out($lang['item.formsection.custom']); ?></legend>

		<dl class="form">
			<?php
			foreach($fields as $field) {
				$value = (isset($item_custom[$field->id])) ? $item_custom[$field->id] : null ;
				?>
				<dt><?php Ecl_Helper_Html::formLabel('custom_field_'. $field->id, $field->name); ?></dt>
				<dd><?php Ecl_Helper_Html::formInput('custom_field_'. $field->id, 50, 250, $value); ?></dd>
				<?php
			}
			?>
		</dl>

	</fieldset>
	<?php
}
?>


<div style="text-align: center;">
	<?php Ecl_Helper_Html::formSubmitUnique('submitsave', $lang['admin.edititem.save_changes']); ?>
</div>


<?php
if (!$new_item) {
	$files = $this->model('itemstore')->findFilesForItem($item);

	$image_files = array();
	$other_files = array();

	if (!empty($files)) {
		$image_ext = array ('jpg', 'jpeg', 'gif', 'png');
		foreach($files as $file) {
			$extension = strtolower(Ecl_Helper_Filesystem::getFileExtension($file->filename));
			if (in_array($extension, $image_ext)) {
				$image_files[] = $file;
			} else {
				$other_files[] = $file;
			}
		}
	}

	$types = $this->model('itemstore')->findAllFileTypes();
	?>

	<fieldset>
		<legend><?php $this->out($lang['item.formsection.resources']); ?></legend>

		<?php
		if (!$this->model('item.allow_embedded_content')) {
			if (!empty($item->embedded_content)) {
				?>
				<div class="section" style="margin-bottom: 2em;">
					<dl class="form">

						<dt>Embedded HTML Content</dt>
						<dd>
							<?php $this->out($item->embedded_content); ?>
							<p class="note">You are not permitted to edit this field.</p>
						</dd>

					</dl>
				</div>
				<?php
			}
		} else {
			?>
			<h2><?php $this->out($lang['item.form.embedded_content']); ?></h2>
			<div class="section" style="margin-bottom: 2em;">
				<dl class="form">

					<dt>Embedded HTML Content</dt>
					<dd>
						<?php Ecl_Helper_Html::formTextarea('embedded_content', 80, 4, $item->embedded_content); ?>
						<p class="note">Use this field to embed videos and other resources, e.g. YouTube videos, RSS feeds, Twitter updates, etc.</p>
					</dd>

				</dl>
			</div>
			<?php
		}
		?>

		<h2><?php $this->out($lang['item.form.links']); ?></h2>
		<div class="section" style="margin-bottom: 2em;">
			<?php
			$links = $this->model('itemlinkstore')->findForItem($item->id);

			if ($links->count() == 0) {
				echo('<p class="note" style="margin-left: 2em;">No links added.</p>');
			} else {
				?>
				<p class="note">The following links have been attached to this item.</p>
				<table class="grid striped" style="margin: 0 0 0 1em;">
				<tr>
					<th>Type</th>
					<th>Title</th>
					<th>Link</th>
					<th>Delete</th>
				</tr>
				<?php
				foreach($links as $i => $link) {
					$tr_class = (($i % 2) == 0) ? 'even' : 'odd' ;
					?>
					<tr class="<?php echo($tr_class); ?>">
						<td><?php Ecl_Helper_Html::formSelect("link[{$link->id}][type]", $types, $link->type); ?></td>
						<td><?php Ecl_Helper_Html::formInput("link[{$link->id}][name]", 25, 250, $link->name); ?></td>
						<td><?php Ecl_Helper_Html::formInput("link[{$link->id}][url]", 40, 250, $link->url); ?></td>
						<td class="checkbox"><?php Ecl_Helper_Html::formCheckbox('delete_link[]', "link_delete_{$i}", $link->id); ?></td>
					</tr>
					<?php
				}
				?>
				</table>
				<?php
			}
			?>

			<h3>Add Links</h3>
			<p class="note">Enter the details for your new link below.</p>

			<dl id="addlink_list" class="form">

				<dt><label>Link 1</label></dt>
				<dd>
					<?php Ecl_Helper_Html::formLabel('newlink[1][name]', 'Title'); ?>
					<br /><?php Ecl_Helper_Html::formInput('newlink[1][name]', 40, 250, '')?>
					<br /><?php Ecl_Helper_Html::formLabel('newlink[1][url]', 'URL'); ?>
					<br /><?php Ecl_Helper_Html::formInput('newlink[1][url]', 65, 250, '')?>
				</dd>

			</dl>

			<div id="addlinksmore_button_container"></div>

		</div>

		<hr />

		<h2>Images</h2>
		<div class="section" style="margin-bottom: 2em;">
			<?php
			if (empty($image_files)) {
				echo('<p class="note" style="margin-left: 2em;">No images uploaded.</p>');
			} else {
				?>
				<p class="note">The following files have been uploaded and attached to this item.</p>
				<p class="note">Select which one will be the main image for the item.  The other images will only appear on the item's detail page.</p>
				<table class="grid striped" style="margin: 0 0 0 1em;">
				<tr>
					<th>Image</th>
					<th>Main Image</th>
					<th>Delete</th>
				</tr>
				<?php
				foreach($image_files as $i => $file) {
					$selected = ($file->filename == $item->image) || (1 == count($image_files));
					$tr_class = (($i % 2) == 0) ? 'even' : 'odd' ;
					?>
					<tr class="<?php echo($tr_class); ?>">
						<td class="name"><?php $this->out($file->filename); ?></td>
						<td class="checkbox"><?php Ecl_Helper_Html::formRadio('use_image', "use_image_{$i}", $file->filename, $selected); ?></td>
						<td class="checkbox"><?php Ecl_Helper_Html::formCheckbox('delete_file[]', "delete_image_{$i}", $file->filename); ?></td>
					</tr>
					<?php
				}
				?>
				</table>
				<?php
			}
			?>
		</div>

		<hr />

		<h2><?php $this->out($lang['item.form.files']); ?></h2>
		<div class="section" style="margin-bottom: 2em;">

			<dl class="form">

				<dt><?php Ecl_Helper_Html::formLabel('copyright_notice', 'Copyright Notice (to cover all uploaded files)'); ?></dt>
				<dd><?php Ecl_Helper_Html::formInput('copyright_notice', 80, 250, $item->copyright_notice)?></dd>

			</dl>


			<?php
			if (empty($other_files)) {
				echo('<p class="note" style="margin-left: 2em;">No additional files uploaded.</p>');
			} else {
				?>
				<p class="note">The following files have been uploaded and attached to this item.</p>
				<p class="note">Organise how they will appear on the details page by giving each file a display name and type.</p>
				<table class="grid striped" style="margin: 0 0 0 1em;">
				<tr>
					<th>File</th>
					<th>Type</th>
					<th>Display Name</th>
					<th>Delete</th>
				</tr>
				<?php
				foreach($other_files as $i => $file) {
					$b64_filename = base64_encode($file->filename);
					$tr_class = (($i % 2) == 0) ? 'even' : 'odd' ;
					?>
					<tr class="<?php echo($tr_class); ?>">
						<td class="name"><?php $this->out($file->filename); ?></td>
						<td><?php Ecl_Helper_Html::formSelect("file_type_{$b64_filename}", $types, $file->type); ?></td>
						<td><?php Ecl_Helper_Html::formInput("file_name_{$b64_filename}", 50, 250, $file->name) ?></td>
						<td class="checkbox"><?php Ecl_Helper_Html::formCheckbox('delete_file[]', "delete_file_{$i}", $file->filename); ?></td>
					</tr>
					<?php
				}
				?>
				</table>
				<?php
			}
			?>

		</div>

		<h2>Upload Images &amp; Files</h2>
		<div class="section">
			<p class="note">Upload files and images associated with this piece of equipment.</p>
			<p class="note">If you upload a file with a name that already exists, it will overwrite the existing file.</p>

			<p class="note">Your server limits uploads to a total of <em><?php echo Ecl_Helper_String::formatBytes($this->php_max_upload); ?></em> per "save".</p>
			<input type="hidden" name="MAX_FILE_SIZE" value="<?php $this->out($this->php_max_upload); ?>" />


			<?php
			if ( (null !== $this->model('item.image.max_width')) || (null !== $this->model('item.image.max_height')) ) {
				?>
				<p class="note">Images are limited to a maximum dimension of
				<em><?php
				if (null === $this->model('item.image.max_width')) {
					echo 'any width';
				} else {
					echo $this->model('item.image.max_width') . ' pixels wide';
				}
				?></em>
				by
				<em><?php
				if (null === $this->model('item.image.max_height')) {
					echo 'any height';
				} else {
					echo $this->model('item.image.max_height') . ' pixels high';
				}
				?></em>
				<br />Any images exceeding these dimensions will be automatically resized.
				<?php
			}
			?>

			<div id="upload">
				<dl class="form">
					<dt><?php Ecl_Helper_Html::formLabel('file_1', 'File 1'); ?></dt>
					<dd><?php Ecl_Helper_Html::formFile('file_1')?></dd>
				</dl>
			</div>

			<div id="uploadmore_button_container"></div>

		</div>
	</fieldset>

	<div style="text-align: center;">
		<?php Ecl_Helper_Html::formSubmitUnique('submitsave', $lang['admin.edititem.save_changes']); ?>
	</div>

	<?php
}// /if(item)
?>



<?php
Ecl_Helper_Html::formClose();
?>


