<?php
$lang = $this->model('lang');
?>

<h1><?php echo $lang['admin.building.header'] ?></h1>


<div class="cf">
	<div class="admin-box">
		<h3><?php echo $lang['admin.building.add'] ?></h3>
		<?php
		Ecl_Helper_Html::form('buildingform', $this->router()->makeAbsoluteUri('/admin/buildings/create/'));
		Ecl_Helper_Html::formHidden('session_key', $this->model('user')->getSessionKey());
		?>
		<dl class="form">

			<dt><?php Ecl_Helper_Html::formLabel('code', $lang['admin.building.code']); ?></dt>
			<dd><?php Ecl_Helper_Html::formInput('code', 10, 10); ?></dd>

			<dt><?php Ecl_Helper_Html::formLabel('name', $lang['admin.building.name']); ?></dt>
			<dd><?php Ecl_Helper_Html::formInput('name', 20, 250); ?></dd>

			<dt><?php Ecl_Helper_Html::formLabel('site_id', $lang['admin.building.site']); ?></dt>
			<dd>
				<?php
				$sites = $this->model('sitestore')->findAll()->toAssoc('id', 'name');

				if (empty($sites)) {
					?>
					<p class="warning">
						<?php echo $lang['admin.building.site_warning'] ?>
						<br /><br />
						<?php echo $lang['admin.building.site_note'] ?>
					</p>
					<?php
				} else {
					Ecl_Helper_Html::formSelect('site_id', $sites);
				}
				?>
			</dd>

			<dt><?php Ecl_Helper_Html::formLabel('latitude', $lang['admin.building.lat']); ?></dt>
			<dd><?php Ecl_Helper_Html::formInput('latitude', 10, 10); ?></dd>

			<dt><?php Ecl_Helper_Html::formLabel('longitude', $lang['admin.building.long']); ?></dt>
			<dd><?php Ecl_Helper_Html::formInput('longitude', 10, 10); ?></dd>

		</dl>

		<div>
			<?php Ecl_Helper_Html::formSubmit('submitadd', $lang['admin.building.submit']); ?>
		</div>

		<?php
		Ecl_Helper_Html::formClose();
		?>
	</div>


	<p><?php echo $lang['admin.building.note'] ?></p>

	<?php
	if ($this->buildings->count()==0) {
		?>
		<p class="warning"><?php echo $lang['admin.building.warning'] ?></p>
		<?php
	} else {
		?>
		<ul>
			<?php
			$edit_stub = $this->router()->makeAbsoluteUri('/admin/buildings/edit/');
			foreach($this->buildings as $i => $building) {
				$edit_url = "{$edit_stub}{$building->id}";
				printf('<li><a href="%2$s">%1$s%3$s</a></li>', Ecl_Helper_Html::escape($building->name), $edit_url, ( !empty($building->code) ? " &nbsp;({$building->code})" : '' ) );
			}
			?>
		</ul>
		<?php
	}
	?>

</div>
