<?php
error_reporting(E_ALL);


$app_root = $this->model('app.root');
$www_root = rtrim($this->router()->makeAbsoluteUri('/'), '/');

$user = $this->model('user');
$lang = $this->model('lang');

//echo '<pre>'; print_r($this->model('menu.category.label'));
//echo '<pre>'; print_r($lang['menu.category.label']);

?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title><?php echo (!empty($this->_title)) ? "{$this->_title} : " : '' ; ?> <?php echo $lang['title'] ?></title>
	<!--bootstrap addition-->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

	<link href="<?php echo $www_root; ?>/css/style.css" media="all" rel="stylesheet" type="text/css" />
	<link href="<?php echo $www_root; ?>/css/print.css" media="print" rel="stylesheet" type="text/css" />

	<link rel="icon" href="<?php echo $lang['favicon'] ?>">

	<?php
	$this->renderStylesheets();
	$this->renderJavascripts();

	if ($this->model('layout.use_local_css')) {
		?>
	<link href="<?php echo $www_root; ?>/local/css/local.css" media="all" rel="stylesheet" type="text/css" />
		<?php
	}

	$this->renderSection('layout.head');

	if ($this->model('layout.use_local_head')) {
		if (file_exists("{$app_root}/local/local_head.html")) {
			include("{$app_root}/local/local_head.html");
		}
	}	
		?>

</head>
<?php echo $this->getSection('layout.pre-body'); ?>
<body>

<div id="wrapper">

	<div id="header">
		<div class="header-wrapper">
			<a class="logo" href="/"><img src="<?php echo $www_root; ?>/images/logo-kc.jpg" alt="Kit-Catalogue" /></a>

			<?php
			$org_logo = $this->model()->get('org.logo');
			$org_www = $this->model()->get('org.www');
			
			if (!empty($org_logo)) {
				if (!empty($org_www)) {
					?>
					<a class="institution" href="<?php echo $org_www; ?>"><img src="<?php echo $www_root; ?>/local/images/<?php echo $org_logo; ?>" alt="<?php echo $this->model('org.title'); ?>" /></a>
					<?php
				} else {
					?>
					<span class="institution"><img src="<?php echo $www_root; ?>/local/images/<?php echo $org_logo; ?>" alt="<?php echo $this->model('org.title'); ?>" /></span>
					<?php
				}
			}
			
			$this->renderSection('layout.header');

			$user = $this->model('user');
			?>
		</div>
	</div>

	<div id="top">

		<div id="nav" class="cf">
			<?php
			if ( (!$user->isAnonymous()) || ($this->model('app.allow_anonymous')) ) {
			?>

			<div id="search-box">
				<form action="<?php echo $www_root; ?>/search/" method="get">
				<input type="text" name="q" id="search" class="hint" value="<?php echo $lang['search'] ?>" onfocus="if (this.value=='<?php echo $lang['search'] ?>') { this.className = ''; this.value = ''; }" onblur="if (this.value == '') { this.className = 'hint'; this.value = '<?php echo $lang['search'] ?>' }" />
				<input type="image" name="searchsubmit" id="search-image" src="<?php echo $www_root; ?>/images/bg-search.png" />	
				</form>
			</div>
		
			<?php 
			} 
			?>

			<ul id="topnav" class="cf">
				
				<?php
				$topnav = array (
					'home'         		=> '/',
					'category'	     	=> "/{$lang['cat.route']}/",
					'department'   		=> "/{$lang['dept.route']}/",
					'ou'           		=> "/ou/",
					'manufacturer' 		=> "/a-z/",
					'facility'     		=> "/facility/",
					'tag'          		=> "/tag/",
				);


				$topnav_order = $this->model("menu.order");
				foreach($topnav as $k => $v) {
					if (!in_array($k, $topnav_order)) {
						$topnav_order[] = $k;
					}
				}

				if ( ($user->isAnonymous()) && (!$this->model('app.allow_anonymous')) ) {
					$topnav = array_intersect_key($topnav, array('home'));
				}

				if ($this->model('app.use_ou_tree')) {
					unset($topnav['department']);
				} else {
					unset($topnav['ou']);
				}


				foreach($topnav_order as $id) {
					if (isset($topnav[$id]) && $this->model("menu.{$id}.enabled")) {
						?>
						<li><a href="<?php echo $www_root . $topnav[$id]; ?>"><?php $this->out($this->model("menu.{$id}.label")); ?></a></li>
						<?php
					}	
				}

				if ($user->isAnonymous()) {
					?>
					<li class="user"><a class="signin" href="<?php echo $www_root; ?>/signin/"> <?php echo $lang['menu.signin.label'] ?> </a></li>
					<?php
				} ?>

				<div class="topnav-right">

				<?php
				if (!isset($_SESSION['lang'])) {
					//echo '<li> <a class="lang" href="?lang=en">en</a></li>';
					echo '<li> <a class="lang "href="?lang=de">de</a></li>';
				} else {
					if ($_SESSION['lang'] !== "en") { echo '<li> <a class="lang" href="?lang=en">en</a></li>';}
					if ($_SESSION['lang'] !== "de") { echo '<li> <a class="lang" href="?lang=de">de</a></li>';}
				}
				?>
				
				</div>
			</ul>
		</div>

		<?php
		if ($this->hasBreadcrumbs()) {
			?>
			<ul id="breadcrumbs">
				<?php $this->renderBreadcrumbs(); ?>
			</ul>
			<?php
		}

		if ( ($user->isAnonymous()) && (true === $this->model('layout.signin_prompt_enabled')) ){
			$signin_prompt = str_replace('[[SIGNIN_URL]]', $this->router()->makeAbsoluteUri('/signin/'), $this->model('layout.signin_prompt'));
			?>
			<p class="signin_warning">
				<?php echo $signin_prompt; ?>
			</p>
			<?php
		}

    	    if (!$user->isAnonymous()) {
        	        ?>
        	<div id="userbar" class="cf">
                	<ul id="usernav">
                        	<li><a href="<?php echo $www_root; ?>/signin/signout"> <?php echo $lang['signin.layout.signout'] ?></a></li>
                        <?php
                        if ($this->model('user')->hasParam(KC__USER_HASITEMS)) {
                                ?>
                                <li><a href="<?php echo $www_root; ?>/myprofile/items"> <?php  echo $lang['signin.layout.myitems'] ?> </a></li>
                                <?php
                        }
                        if ($this->model('security')->checkAuth(KC__AUTH_CANADMIN)) {
                                ?>
                                <li><a href="<?php echo $www_root; ?>/admin"> <?php echo $lang['signin.layout.admin']  ?> </a></li>
                                <?php
                        } elseif ($this->model('security')->checkAuth(KC__AUTH_CANOUADMIN)) {
                                ?>
                                <li><a href="<?php echo $www_root; ?>/ouadmin"> <?php echo $lang['signin.layout.ouadmin'] ?> </a></li>
                                <?php
                        }
                        ?>
                        <li> <?php echo $lang['signin.layout.welcome'] ?> <strong><?php
                                $name = $user->name;
                                if (empty($name)) {
                                        $name = $user->email;
                                }
                                $this->out($name);
                        ?></strong></li>
                </ul>
       	 </div>
                <?php
        		}
        	?>
	</div>




	<?php
	$this->renderFeedback();

	$this->renderSection('layout.pre-content');

	echo $this->content();

	$this->renderSection('layout.post-content');
	?>
	<div id="footer">

		<?php $this->renderSection('layout.footer'); ?>

		<p><a class="link" href="mailto:<?php $this->out($this->model('app.email')); ?>"><?php echo $lang['footer.contactowner'] ?></a></p>

		<?php $this->renderView('snippets_licenceinfo', ''); ?>

		<p><?php echo $lang['footer.poweredby'] ?> <br>
		<?php echo $lang['footer.license'] ?></p>
	</div>
</div>

<?php $this->renderSection('layout.post-body'); ?>

<iframe src="<?php echo $www_root; ?>/keep_alive.php" height="1" width="1" style="display: none;">keep alive</iframe>



</body>
</html>
