<?php
$item = $this->item;
$form = $this->form;

$lang = $this->model('lang');

$back_url = base64_encode($this->backlink);

$this->layout()->addBreadcrumb('Item', $this->router()->makeAbsoluteUri($this->backlink));
$this->layout()->addBreadcrumb('Item Enquiry', $this->router()->makeAbsoluteUri("/enquiry/{$item->id}?backlink={$back_url}"));
?>


<h1> <?php echo $lang['enquiry.header.label'] ?> </h1>
<p class="note"> <?php echo $lang['enquiry.note.form'] ?> </p>
<p class="note"> <?php echo $lang['enquiry.note.fineprint'] ?> </p>

<?php
Ecl_Helper_Html::form('enquiryform', $this->router()->makeAbsoluteUri("/enquiry/{$item->id}?backlink={$back_url}"));
?>


<input type="submit" name="submitfake" value="fake" onclick="return false;" style="position: absolute; left: -100%;" />

<fieldset>
	<legend> <?php echo $lang['enquiry.form.equip_info'] ?> </legend>
	<table class="fields" style="margin-left: 2em;">
	<tr>
		<th> <?php echo $lang['enquiry.form.name'] ?> </th>
		<td><?php $this->out($item->name); ?></td>
	</tr>
	<tr>
		<th> <?php echo $lang['enquiry.form.location'] ?> </th>
		<td><?php $this->out($this->model('organisationalunitstore')->lookupName($item->ou)); ?></td>
	</tr>
	<?php
	if (!empty($item->access)) {
		?>
		<tr>
			<th> <?php echo $lang['enquiry.form.access'] ?> </th>
			<td><?php $this->out($this->model('accesslevelstore')->lookupName($item->access)); ?></td>
		</tr>
		<?php
	}
	?>
	</table>
</fieldset>

<fieldset>
	<legend> <?php echo $lang['enquiry.form.details'] ?> </legend>
	<table class="layout">
	<tr>
		<td>
			<dl class="form" style="margin-left: 2em;">

				<dt><?php Ecl_Helper_Html::formLabel('name', $lang['enquiry.form.name'].' *'); ?></dt>
				<dd>
					<p class="note"> <?php echo $lang['enquiry.form.namehelp'] ?> </p>
					<?php Ecl_Helper_Html::formInput('name', 30, 250, $form['name']); ?>
				</dd>

				<dt><?php Ecl_Helper_Html::formLabel('email', $lang['enquiry.form.email'].' *'); ?></dt>
				<dd>
					<p class="note"> <?php echo $lang['enquiry.form.emailhelp'] ?> </p>
					<?php Ecl_Helper_Html::formInput('email', 40, 250, $form['email']); ?>
				</dd>

				<dt><?php Ecl_Helper_Html::formLabel('phone', $lang['enquiry.form.phone']); ?></dt>
				<dd>
					<p class="note"> <?php echo $lang['enquiry.form.phonehelp'] ?> </p>
					<?php Ecl_Helper_Html::formInput('phone', 20, 20, $form['phone']); ?>
				</dd>

			</dl>
		</td>
		<td>
			<dl class="form" style="margin-left: 5em;">

				<dt><?php Ecl_Helper_Html::formLabel('org', $lang['enquiry.form.org']); ?></dt>
				<dd>
					<p class="note"> <?php echo $lang['enquiry.form.orghelp'] ?> </p>
					<?php Ecl_Helper_Html::formInput('org', 40, 250, $form['org']); ?>
				</dd>

				<dt><?php Ecl_Helper_Html::formLabel('role', $lang['enquiry.form.job']); ?></dt>
				<dd>
					<p class="note"> <?php echo $lang['enquiry.form.jobhelp'] ?> </p>
					<?php Ecl_Helper_Html::formInput('role', 40, 250, $form['role']); ?>
				</dd>

				<dt><?php Ecl_Helper_Html::formLabel('deadline', $lang['enquiry.form.deadline']); ?></dt>
				<dd>
					<p class="note"> <?php echo $lang['enquiry.form.deadlinehelp'] ?> </p>
					<?php Ecl_Helper_Html::formInput('deadline', 40, 50, $form['deadline']); ?>
				</dd>

			</dl>
		</td>
	</tr>
	</table>
</fieldset>

<fieldset>
	<legend> <?php echo $lang['enquiry.form.enquiry'] ?> </legend>
	<dl class="form" style="margin-left: 2em;">

		<dt><?php Ecl_Helper_Html::formLabel('type', $lang['enquiry.form.typ']); ?></dt>
		<dd>
			<?php
			$options = array(
				'general'   => $lang['enquiry.form.option.genenq'] ,
				'booking'   => $lang['enquiry.form.option.bookreq'] ,
				'research'  => $lang['enquiry.form.option.rescollab'] ,
			);
			Ecl_Helper_Html::formSelect('type', $options, $form['type']);
			?>
		</dd>

		<dt><?php Ecl_Helper_Html::formLabel('body', $lang['enquiry.form.text'].' *'); ?></dt>
		<dd>
			<p class="note"> <?php echo $lang['enquiry.form.texthelp'] ?> </p>
			<?php Ecl_Helper_Html::formTextarea('body', 80, 6, $form['body']); ?>
		</dd>

	</dl>

</fieldset>

<?php
if ( $this->model('enquiry.use_recaptcha') && (!Ecl::isEmpty($this->model('recaptcha.public_key'))) && (!Ecl::isEmpty($this->model('recaptcha.private_key'))) ) {
	$recaptcha_error = $this->recaptcha_error;
	?>
	<fieldset>

		<dl class="form">

			<dt> <?php echo $lang['enquiry.form.antispam'] ?> </dt>
			<dd>
				<?php
				$use_ssl = (strpos($this->router()->makeAbsoluteUri('/'), 'https')===0);
				require_once($this->model('app.include_root').'/library/recaptcha/recaptchalib.php');
				echo recaptcha_get_html($this->model('recaptcha.public_key'), $recaptcha_error, $use_ssl);
				?>
			<dd>

		</dl>
	</fieldset>
	<?php
}
?>

<div class="button_bar">
	<?php Ecl_Helper_Html::formSubmit('submitcancel', $lang['enquiry.form.cancel']); ?>
	<?php Ecl_Helper_Html::formSubmit('submitsend', $lang['enquiry.form.send']); ?>
</div>

<?php
Ecl_Helper_Html::formClose();
?>

