<?php

$lang = $this->model('lang');

$www_root = $this->model('app.www');

$this->layout()->appendSection('layout.head', '
	<!-- INSTALL.REWRITE=OK (This string is checked for as part of the installation process) -->
	<style type="text/css">

		#signonform { margin-bottom: 1em; }

	</style>
	<script type="text/javascript">

		window.onload = function() {
			var uname = document.getElementById("username");
			uname.focus();
		}

	</script>
');


$this->layout()->addBreadcrumb('Sign In', $this->router()->makeAbsoluteUri('/signin/'));



switch (strtolower($this->request()->get('msg'))) {
	case 'failed':
		$this->layout()->addFeedback(KC__FEEDBACK_ERROR , 'Your username and password were rejected.' ,	'Please check your username and password and try again.');
		break;
	case 'signedout':
		$this->layout()->addFeedback(KC__FEEDBACK_SUCCESS ,	'You have signed out.');
		break;
	case 'notsupported':
		$this->layout()->addFeedback(KC__FEEDBACK_ERROR, 'The authentication method selected is not supported.', 'Please use another sign-in option and try again.');
		break;
	default:
		break;
}



?>

<h1> <?php echo $lang['signin.header.head']  ?></h1>
<?php
$use_https = $this->model('app.use_https') ? true : false ;
?>
<form action="<?php echo $this->router()->makeAbsoluteUri('/signin/check/', $use_https); ?>" method="post" id="signonform">

<div style="float: left;">
	<table class="form" style="margin-left: 5em;">
	<tr>
		<th><?php Ecl_Helper_Html::formLabel('username', $lang['signin.form.username']); ?></th>
		<td><?php Ecl_Helper_Html::formInput('username', '12', '50'); ?></td>
	</tr>
	<tr>
		<th><?php Ecl_Helper_Html::formLabel('password', $lang['signin.form.password']); ?></th>
		<td><?php Ecl_Helper_Html::formPassword('password', '12', '50'); ?></td>
	</tr>
	<tr>
		<td colspan="2" style="padding-top: 1em; text-align: right;">
			<?php Ecl_Helper_Html::formSubmit('signin', $lang['signin.form.submit']); ?>
		</td>
	</tr>
	</table>
</div>

<?php
if ($this->model('signin.use_shibboleth')) {
	?>
	<div class="sso-box">
		<p> <?php echo $lang['signin.sso.box']  ?></p>
		<div><a class="sso-link" href="/sso/">Use Single Sign-On</a></div>
	</div>
	<?php
}
?>

<div style="clear: both;"></div>

</form>

<br />
<br />

<h3> <?php echo $lang['signin.allowsyou.head']?> </h3>
<ul style="margin-left: 2em; list-style: disc;">
	<li> <?php echo $lang['signin.allowsyou.browse']?>  </li>
	<li> <?php echo $lang['signin.allowsyou.location']?>  </li>
	<li> <?php echo $lang['signin.allowsyou.manuals']?>  </li>
</ul>

