<?php
$lang = $this->model('lang');
$ou_label_lower = strtolower($lang['ou.label']);
$ou_plural_lower = strtolower($lang['ou.label.plural']);

$user = $this->user;
$new_user = $this->new_user;


$this->layout()->addGlobalJavascript();


if ($this->model('user')->username != $user->username) {
	$this->layout()->appendSection('layout.head', <<<EndJS
	<script type="text/javascript">

		$(document).ready( function() {

			var del_button = $('<input type="submit" name="submitdelete" value="Delete Use" />');
			del_button.click(function () {
				return confirm('Please confirm that you want to delete this user.\\n\\nThis operation cannot be undone.');
			});
			$('#delete_button_container').append(del_button);

		});

	</script>
	<style type="text/css">

		:checked + label { font-weight: bold; }

	</style>
EndJS
	);
}
?>


<?php
Ecl_Helper_Html::form('userform', $this->request()->uri(), 'post', 'UTF-8');
Ecl_Helper_Html::formHidden('session_key', $this->model('user')->getSessionKey());
if (!$new_user) {
	Ecl_Helper_Html::formHidden('username', $user->username);
}
?>


<input type="submit" name="submitsave" value="Save Changes" style="position: absolute; left: -100%;" />


<div id="delete_button_container"></div>


<h1><?php echo $lang['admin.useredit.header']; $this->out("{$user->name} ({$user->username})"); ?></h1>

<div class="cf">

	<div class="admin-box">
		<h3> <?php echo $lang['admin.useredit.changepw'] ?> </h3>
		<div class="section">
			<?php
			if ($this->model('signin.use_ldap')) {
				?>
				<p> <?php echo $lang['admin.useredit.ldap_precedence'] ?> </p>
				<p> <?php echo $lang['admin.useredit.password_effect'] ?> </p>
				<p> <?php echo $lang['admin.useredit.admin_example'] ?> </p>
				<?php
			}

			if (!$this->model('signin.use_database')) {
				?>
				<p>Kit-Catalogue is NOT using database authentication, so any password changes here will be irrelevant to the current sign-in setup.</p>
				<?php
			}
			?>
			<dl class="form">
				<dt><?php Ecl_Helper_Html::formLabel('password', $lang['admin.user.label_password'] ); ?></dt>
				<dd><?php Ecl_Helper_Html::formPassword('password', 20, 50, ''); ?></dd>

				<dt><?php Ecl_Helper_Html::formLabel('confirm_password', $lang['admin.user.label_password_confirm'] ); ?></dt>
				<dd><?php Ecl_Helper_Html::formPassword('confirm_password', 20, 50, ''); ?></dd>
			</dl>
		</div>

		<div>
			<?php Ecl_Helper_Html::formSubmit('submitcancel', $lang['admin.useredit.cancel'] ); ?>
			<?php Ecl_Helper_Html::formSubmit('submitsave2', $lang['admin.useredit.save'] ); ?>
		</div>
	</div>

	<p> <?php echo $lang['admin.useredit.details'] ?> </p>
	<p class="note"> <?php echo $lang['admin.useredit.fineprint'] ?> </p>
	<?php
	$this->render('users_snippets_editsubform');
	?>

	<div style="margin: 0 0 20px 10em;">
		<?php Ecl_Helper_Html::formSubmitUnique('submitsave', $lang['admin.useredit.save']); ?>
	</div>

	<h3> <?php echo $lang['admin.useredit.permissions'] ?> </h3>
	<fieldset>
		<legend> <?php echo $lang['admin.useredit.systemwide'] ?> </legend>
		<div class="section">
			<?php
			$available_perms = array (
				KC__AUTH_CANADMIN  => $lang['admin.useredit.adm'] ,
			);

			$current_perms = $this->model('sysauth')->FindAuthsForAgentItem($user->username, 'system');

			// Users cannot edit their own System Authorisations
			if ($this->model('user')->username != $user->username) {
				Ecl_Helper_Html::formCheckboxGrid('auth_system', $available_perms, 1, $current_perms);
			} else {
				?>
				<div class="feedback feedback_info" style="margin: 0;">
					<p class="title">You cannot edit your own System-Wide Permissions.</p>
					<?php
					if (empty($current_perms)) {
						// If a user ever sees this message, we have security problems!
						echo('<p>You have no current system permissions.</p>');
					} else {
						echo('<p>Your current system permissions are:</p>');
						echo('<ul>');
						foreach($current_perms as $perm) {
							if (isset($available_perms[$perm])) {
								echo("<li>{$available_perms[$perm]}</li>");
							}
						}
						echo('</ul>');
					}
					?>
				</div>
				<?php
			}
			?>
		</div>
	</fieldset>


	<fieldset>
		<legend> <?php echo $lang['admin.useredit.specific'] ?> </legend>
		<p class="note"> <?php echo $lang['admin.useredit.orgspecific'] ?> </p>
		<p class="note"> <?php echo $lang['admin.useredit.inclusive'] ?> </p>

		<div id="tree" style="padding: 0.4em; background-color: #fff; ">
			<?php
			$ou_list = $this->model('organisationalunitstore')->findTree()->toArray();
			if (empty($ou_list)) {
				?>
				<p class="warning">
					No <?php echo $this->out($ou_label_lower); ?> have been created.
				</p>
				<?php
			} else {

				function renderTree($tree, $callback = null, $current_level = null) {
					if (null === $current_level) {
						$current_level = -1;
					} else {
						$current_level = (int) $current_level;
					}

					$node = array_shift($tree);

					$indent = str_repeat("\t", $node->tree_level);

					if ($node->tree_level > $current_level) {
						echo("\n{$indent}<ul>");
					} elseif ($node->tree_level < $current_level) {
						$closing_indent = str_repeat("\t", $current_level);
						echo str_repeat("\n{$closing_indent}</ul>", $current_level - $node->tree_level);
					}

					echo "\n{$indent}";
					if (is_callable($callback)) {
						$callback($node);
					} else {
						$name = (!empty($node->name)) ? $node->name : '<unknown>' ;
						echo "<li>{$name}";
					}

					if (!empty($tree)) {
						renderTree($tree, $callback, $node->tree_level);

						if ($node->tree_level > $current_level) {
							echo str_repeat("\n</ul>\n", $node->tree_level);
						}
					}

					return true;
				}

				$curr_auths = $this->model('sysauth')->findItemsForAgent($user->username);
				if (empty($curr_auths)) { $curr_auths = array(); }

				$that = $this;
				renderTree($ou_list, function($node) use ($that, $curr_auths) {
					$name = (!empty($node->name)) ? $node->name : '<unknown>' ;
					if (0 == $node->tree_level) {
						printf('<li> %1$s ', $that->escape($name));
					} else {
						echo '<li> ';
						Ecl_Helper_Html::formCheckbox('permissions[]', 'permission_'.$node->id, "ou_{$node->id}", (in_array("ou_{$node->id}", $curr_auths)));
						Ecl_Helper_Html::formLabel('permission_'.$node->id, $that->escape($name));
					}
				});
			}
			?>
		</div>
	</fieldset>

	<div class="button_bar">
		<?php Ecl_Helper_Html::formSubmitUnique('submitsave', $lang['admin.useredit.save']); ?>
	</div>

</div>


<?php
Ecl_Helper_Html::formClose();
?>


