<?php 
$lang = $this->model('lang');
?>

<h1> <?php echo $lang['admin.user.header'] ?> </h1>

<div class="cf">


	<?php
	if ($this->model('signin.use_ldap')) {
		?>
		<div class="admin-box" style="background-color: #eee;">
			<p style="font-weight: bold;"> <?php echo $lang['admin.user.ldapboldnote'] ?> </p>
			<p> <?php echo $lang['admin.user.ldapnote1'] ?> </p>
			<p> <?php echo $lang['admin.user.ldapnote2'] ?> </p>
			<p> <?php echo $lang['admin.user.ldapnotetu'] ?> </p>
		</div>
		<?php
	}
	?>


	<div class="admin-box">
		<h3> <?php echo $lang['admin.user.add_new'] ?> </h3>
		<?php
		Ecl_Helper_Html::form('userform', $this->router()->makeAbsoluteUri('/admin/users/create/'));
		Ecl_Helper_Html::formHidden('session_key', $this->model('user')->getSessionKey());
		?>
		<dl class="form">
			<dt><?php Ecl_Helper_Html::formLabel('username',  $lang['admin.user.label_username'] ); ?></dt>
			<dd><?php Ecl_Helper_Html::formInput('username', 16, 250); ?></dd>

			<dt><?php Ecl_Helper_Html::formLabel('forename',  $lang['admin.user.label_forename'] ); ?></dt>
			<dd><?php Ecl_Helper_Html::formInput('forename', 25, 250); ?></dd>

			<dt><?php Ecl_Helper_Html::formLabel('surname', $lang['admin.user.label_surname'] ); ?></dt>
			<dd><?php Ecl_Helper_Html::formInput('surname', 25, 250); ?></dd>

			<dt><?php Ecl_Helper_Html::formLabel('email', $lang['admin.user.label_email'] ); ?></dt>
			<dd><?php Ecl_Helper_Html::formInput('email', 25, 250); ?></dd>

			<dt><?php Ecl_Helper_Html::formLabel('password', $lang['admin.user.label_password'] ); ?></dt>
			<dd><?php Ecl_Helper_Html::formPassword('password', 20, 50, ''); ?></dd>

			<dt><?php Ecl_Helper_Html::formLabel('confirm_password',  $lang['admin.user.label_password_confirm'] ); ?></dt>
			<dd><?php Ecl_Helper_Html::formPassword('confirm_password', 20, 50, ''); ?></dd>
		</dl>

		<div>
			<?php
			Ecl_Helper_Html::formSubmit('submitadd',  $lang['admin.user.add_user_button'] );
			?>
		</div>
		<?php
		Ecl_Helper_Html::formClose();
		?>
	</div>


	<p> <?php echo $lang['admin.user.usernote'] ?> </p>


	<?php
	$users = $this->model('userstore')->findAll();
	if ($users->count()==0) {
		?>
		<p class="warning"> <?php echo $lang['admin.user.no_users'] ?> </p>
		<?php
	} else {
		?>
		<ul>
			<?php
			foreach($users as $i => $user) {
				printf('<li><a href="%2$s">%1$s</a></li>', $this->escape("{$user->sortname} &nbsp; ({$user->username})"), $this->router()->makeAbsoluteUri("/admin/users/edit/{$user->url_username}"));
			}
			?>
		</ul>
		<?php
	}
	?>
</div>
